### ISSUE TITLE
Request to port GATK 'Exome Germline Single Sample' pipeline to Cromwell on Azure

### ISSUE THREAD

**Issue by superbsky** [microsoft/gatk4-genome-processing-pipeline-azure#6]
I would like to request the porting of the GATK 'Exome Germline Single Sample' pipeline to Cromwell on Azure. I noticed that the pipeline is currently available on GitHub (https://github.com/broadinstitute/warp/tree/master/pipelines/broad/dna_seq/germline/single_sample/exome) and would like to inquire if there are any plans to make it available on Cromwell on Azure.

As a user, I would find this porting beneficial for my work and would appreciate any information on the timeline for this project.

Thank you for your attention to this request.

**Comment by vsmalladi** [comment]
@superbsky, We have worked with the broad and there should be no changes needed to support navtivley the warp repos in azure. If there are any issues running on Azure. Please open an issue in WARP repo and we can help address it
